version: "3.2"
services:
  app:
    build: .
    command: sh -c '/usr/app/wait-for mock:1880 -- npm run start'
    depends_on:
      - mock
      - nginx
    environment:
      HTTP_PROXY: http://nginx:8080
  mock:
    build: ./mock
    ports:
      - "1880:1880"
    volumes:
      - ./mock/src:/data
  nginx:
    depends_on:
      - mock
    image: nginx:1.16-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf